### ✦ Leia o arquivo do datase em csv;

In [10]:
import pandas as pd

read_netflix = pd.read_csv('netflix.csv')
read_netflix

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8812,s5202,Movie,Joan Didion: The Center Will Not Hold,Griffin Dunne,Joan Didion,United States,"October 27, 2017",2017,TV-14,98 min,Documentaries,Literary icon Joan Didion reflects on her rema...
8813,s2914,Movie,Fanatyk,Michał Tylka,"Piotr Cyrwus, Mikołaj Kubacki, Anna Radwan, Ma...",Poland,"February 14, 2020",2017,TV-MA,33 min,"Comedies, Dramas, Independent Movies","As a son deals with his own struggles, he must..."
8814,s3710,Movie,ANIMA,Paul Thomas Anderson,Thom Yorke,United Kingdom,"June 27, 2019",2019,TV-PG,15 min,"Dramas, Independent Movies, Music & Musicals",In a short musical film directed by Paul Thoma...
8815,s516,TV Show,Derry Girls,NaN,"Saoirse-Monica Jackson, Nicola Coughlan, Louis...",United Kingdom,"July 6, 2021",2019,TV-MA,2 Seasons,"British TV Shows, International TV Shows, TV C...",Amidst the political conflict of Northern Irel...
8816,s2827,TV Show,On My Block,NaN,"Sierra Capri, Jason Genao, Brett Gray, Diego T...",United States,"March 11, 2020",2020,TV-14,3 Seasons,"Romantic TV Shows, TV Comedies, TV Dramas",In a rough inner-city Los Angeles neighborhood...

### ✦ Visualize as primeiras linhas do dataset;

In [11]:
print(read_netflix.head())

  show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                                cast        country  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min
1  September 24, 2021          2021  TV-MA  2 Seasons
2  September 24, 2021          2021  TV-MA   1 Season
3  September 24, 2021          2021  TV-MA   1 Season
4  September 24, 2021          2021  TV-MA  2 Seasons

                                           listed_in  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

                                         description
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
3  Feuds, flirtations and toilet talk go down amo...
4  In a city of coaching centers known to train I...

### ✦ Visualize informações básicas do dataset, como: nomes das colunas, número de linhas, número de campos nulos, etc;

In [12]:
read_netflix.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [13]:
read_netflix.shape

(8817, 12)

In [14]:
print(read_netflix.isnull().sum())

show_id            0
type               0
title              0
director        2638
cast             825
country          832
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

### ✦ Visualize informações sobre os campos numéricos do dataset, como: média, valor minimo e maximo, etc;

In [15]:
read_netflix.info()
read_netflix.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8817 entries, 0 to 8816
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8817 non-null   object
 1   type          8817 non-null   object
 2   title         8817 non-null   object
 3   director      6179 non-null   object
 4   cast          7992 non-null   object
 5   country       7985 non-null   object
 6   date_added    8807 non-null   object
 7   release_year  8817 non-null   int64
 8   rating        8813 non-null   object
 9   duration      8814 non-null   object
 10  listed_in     8817 non-null   object
 11  description   8817 non-null   object
dtypes: int64(1), object(11)
memory usage: 826.7+ KB

       release_year
count   8817.000000
mean    2014.180333
std        8.817990
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

### ✦ Remova informações nulas;

In [16]:
remove_null = read_netflix.dropna()

print(remove_null)

     show_id     type                                  title  \
7         s8    Movie                                Sankofa
8         s9  TV Show          The Great British Baking Show
9        s10    Movie                           The Starling
12       s13    Movie                           Je Suis Karl
24       s25    Movie                                  Jeans
...      ...      ...                                    ...
8809   s4020    Movie                   Everything About Her
8810   s6033    Movie                      A Dangerous Woman
8812   s5202    Movie  Joan Didion: The Center Will Not Hold
8813   s2914    Movie                                Fanatyk
8814   s3710    Movie                                  ANIMA

                  director                                               cast  \
7             Haile Gerima  Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...
8          Andy Devonshire  Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...
9           Theodore Melfi  Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...
12     Christian Schwochow  Luna Wedler, Jannis Niewöhner, Milan Peschel, ...
24              S. Shankar  Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...
...                    ...                                                ...
8809          Joyce Bernal  Angel Locsin, Xian Lim, Vilma Santos, Michael ...
8810    Stephen Gyllenhaal  Debra Winger, Barbara Hershey, Gabriel Byrne, ...
8812         Griffin Dunne                                        Joan Didion
8813          Michał Tylka  Piotr Cyrwus, Mikołaj Kubacki, Anna Radwan, Ma...
8814  Paul Thomas Anderson                                         Thom Yorke

                                                country          date_added  \
7     United States, Ghana, Burkina Faso, United Kin...  September 24, 2021
8                                        United Kingdom  September 24, 2021
9                                         United States  September 24, 2021
12                              Germany, Czech Republic  September 23, 2021
24                                                India  September 21, 2021
...                                                 ...                 ...
8809                                        Philippines      March 14, 2019
8810                                      United States       April 1, 2018
8812                                      United States    October 27, 2017
8813                                             Poland   February 14, 2020
8814                                     United Kingdom       June 27, 2019

      release_year rating   duration  \
7             1993  TV-MA    125 min
8             2021  TV-14  9 Seasons
9             2021  PG-13    104 min
12            2021  TV-MA    127 min
24            1998  TV-14    166 min
...            ...    ...        ...
8809          2016  TV-MA    127 min
8810          1993      R    101 min
8812          2017  TV-14     98 min
8813          2017  TV-MA     33 min
8814          2019  TV-PG     15 min

                                             listed_in  \
7     Dramas, Independent Movies, International Movies
8                         British TV Shows, Reality TV
9                                     Comedies, Dramas
12                        Dramas, International Movies
24     Comedies, International Movies, Romantic Movies
...                                                ...
8809            Comedies, Dramas, International Movies
8810                           Dramas, Romantic Movies
8812                                     Documentaries
8813              Comedies, Dramas, Independent Movies
8814      Dramas, Independent Movies, Music & Musicals

                                            description
7     On a photo shoot in Ghana, an American model s...
8     A talented batch of amateur bakers face off in...
9     A woman adjusting to life after a loss contend...
12    After most of her family is murdered in a terr...
24    When the father of the man she loves insists t...
...                                                 ...
8809  A hard-driving real estate tycoon who becomes ...
8810  At the center of this engrossing melodrama is ...
8812  Literary icon Joan Didion reflects on her rema...
8813  As a son deals with his own struggles, he must...
8814  In a short musical film directed by Paul Thoma...

[5338 rows x 12 columns]

### ✦ Verifique se existem dados duplicados;

### ✦ Remova informações duplicadas;

### ✦ Remova as colunas 'listed_in' e 'duration'.